### ISSUE TITLE
Forest data model (conversion): Forest center number missing with SMK XML

### ISSUE THREAD

**Issue by Sorvalampi** [lukefi/metsi#22]
Forest data model (conversion): Forest center number missing with SMK XML.

Should be an integer value between 0...13.

**Comment by Sorvalampi** [comment]
If so, so leave it. Set it to be -1 (0 actually means Ahvenanmaa so do use 0).

**Comment by jpy-luke** [comment]
This is now set to -1. Proper source for this needs to be established in XML file creation or by creating a separate process to augment the XML file.

**Comment by jpy-luke** [comment]
https://github.com/menu-hanke/smk-browser/issues/27 proposed for adding this properly into the XML.
