### ISSUE TITLE
Forest data model (conversion): Forest management category number missing with SMK XML.

### ISSUE THREAD

**Issue by Sorvalampi** [lukefi/metsi#23]
Forest data model (conversion): Forest management category number missing with SMK XML.

Use 1 as this information may not be present in SMK XML.

**Comment by jpy-luke** [comment]
Current implementation uses StandBasicData.CuttingRestriction as the source for this value. I will make this default to 1 when value doesn't exist but retain the existing implementation.

**Comment by jpy-luke** [comment]
This is now set to 1 when it would otherwise resolve to None from XML source.
