### ISSUE TITLE
Forest data model (conversion): Municipality number missing with SMK XML

### ISSUE THREAD

**Issue by Sorvalampi** [lukefi/metsi#24]
Forest data model (conversion): Municipality number missing with SMK XML.

Should be near the end of stand info row.

**Comment by jpy-luke** [comment]
This is now set to -1 for SMK XML source. Proper source for the data needs to be established in creation of the XML file or by creating a separate process for augmenting that file.

**Comment by jpy-luke** [comment]
https://github.com/menu-hanke/smk-browser/issues/27 proposed for adding this properly into the XML.
