### ISSUE TITLE
ReferenceTree - TreeStratum binding

### ISSUE THREAD

**Issue by jpy-luke** [lukefi/metsi#27]
We need a way to connect VMI tree rows to stratum rows. We don't want to introduce this association into the main model.
Create a function which establishes a dict which binds a stratum identifier to a list of tree identifiers.
This function is `list[TreeStratum], list[ReferenceTree] => dict[str, list[str]]`

TODO: we don't have a proper rule for establishing this association yet. The strongest key we have is to associate a tree to a stratum using species, but there may be multiple strata with same species. Expert input is needed to establish a rule.

**Comment by Sorvalampi** [comment]
In VMI12, each tree has a variable called canopy layer ('latvuskerros'). This additional info should be used in determining to which stratum a measured belongs. It is also possible that a measured tree does not belong to any stratum. This is the case of e.g. big distinct trees ('säästöpuu'). A stratum data is collected only if the basal area of a tree species with certain canopy layer exceeds 1 m2/ha.
