### ISSUE TITLE
Runtime error in preprocessing XML

### ISSUE THREAD

**Issue by Sorvalampi** [lukefi/metsi#32]
Runtime error in preprocessing XML.

The error message is "'ForestStand' object has no attribute 'soil_and_peatland_category'".

All the files needed in tests in the attached zip file.

[Kajaani.zip](https://github.com/lukefi/metsi/files/11610532/Kajaani.zip)

**Comment by jpy-luke** [comment]
This data set triggered a previously unvisited code path for stand management operations management where there was a typo for this ForestStand property. Should be `soil_peatland_category` instead of `soil_and_peatland_category`. Fixed in main branch now.
