### ISSUE TITLE
Data conversion with VMI12: area weights are faulty in side compartments in rsd output file

### ISSUE THREAD

**Issue by Sorvalampi** [lukefi/metsi#40]
Data conversion with VMI12: area weights are faulty in side compartments. This seems to appear only in rsd files.

For example:
========
Compartment number 0006023 02 2: 
actual area  = 230.8291
osuus9m = 02
The conversion produces: 230.8291. 
The correct area is 0,2*230.8291 = 46.16582.

Another example:
===========
Compartment number 0007023 03 2
actual area  = 230.8291
osuus9m = 05
The conversion produces: 230.8291. 
The correct area is 0,5*230.8291 = 115.41455

**Comment by Sorvalampi** [comment]
@jpy-luke  Could you check this immediately. Seems that side compartments (the ones with compartment nr>1) get the full area value instead of a right share.

**Comment by Sorvalampi** [comment]
As stated in the title, this appears to be the problem only in rsd output files. Area data seems to be ok, in csv files.

**Comment by Sorvalampi** [comment]
As a hotfix, the following change was made:
default_mela_tree_mappers = [species_mapper]
default_mela_stratum_mappers = [species_mapper]
default_mela_stand_mappers = [stand_location_converter,
                              #stand_area_converter,
                              owner_mapper, 
                              land_use_mapper, 
                              site_type_mapper, 
                              soil_peatland_mapper,
                              drainage_category_mapper]

i.e.  stand_area_converter was commented.

This was invented by @reettalempinen and (for tests) updated to local versions . So @jpy-luke please check if this is a valid correction and update the official version.

**Comment by jpy-luke** [comment]
The stand_area_converter is a RSD specific output converter which assumes 
```
    if target.is_auxiliary():
        target.area_weight = target.area
        target.area = 0.0
```
where target is a ForestStand. I believe auxiliary means side compartment (compartment is new lingo to me).

#36 made area_weight an independent thing in input handling already, but this of course overrides it.

So. Let's assume that area and area_weight are now computed correctly. Is the result correct if I just remove the area_weight override from this?

**Comment by Sorvalampi** [comment]
So. Let's assume that area and area_weight are now computed correctly. Is the result correct if I just remove the area_weight override from this? 

Yes, I think so.
