### ISSUE TITLE
Data conversion with VMI12: actual areas are faulty in side compartments in csv output file

### ISSUE THREAD

**Issue by Sorvalampi** [lukefi/metsi#41]
Data conversion with VMI12: actual areas are faulty in side compartments in csv output file.

In the case of side compartments (stand nr>1) the actual areas must always equal to zero.

Now they seem to be same as in the main compartment.

For example: 
Main compartment:
stand;0-006-023-02-1;29;2018;230.8291;184.66328000000001;
THIS IS FINE.

Side compartment:
stand;0-006-023-02-2;30;2018;230.8291;46.165820000000004;
SHOULD BE:
stand;0-006-023-02-2;30;2018;000.0000;46.165820000000004;

**Comment by Sorvalampi** [comment]
This issue to be notified also by @reettalempinen-

**Comment by Sorvalampi** [comment]
The original issue was #36

**Comment by jpy-luke** [comment]
This is not a regression from #36 . From the beginning of our history, area is the determined for each ForestStand with 
[https://github.com/lukefi/metsi/blob/7165babc3d817b12006371dbd3e7474c18a11f38/lukefi/metsi/data/formats/vmi_util.py#L96](a table lookup). Compartment has not been a concept in this.

So an alternative for side compartments needs to be added as a **new feature**.

**Comment by jpy-luke** [comment]
So the thing is, if we set area to 0, this will have serious implications in further processing for calculating. Area is a critical primary variable in several simulation operations and can not be just set to 0. This issue needs a step back for a proper design.

**Comment by Sorvalampi** [comment]
OK. Let's leave this one at the moment and think it again later.

**Comment by dmela** [comment]
Solved in #46
